-- member table 생성
-- generated by default as identity : insert시 값지정안하고 자동으로 생성해줌
drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);